### ISSUE TITLE
AI Calculator

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [abhisheks008/Play-With-Python#193]
### Play With Python Repository (Proposing new issue)
:red_circle: **AI Calculator** : </br>
:red_circle: **Calculator with the power of artificial intelligence** : </br>

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Soumya Kushwaha
- GitHub Profile Link : https://github.com/Soumya-Kushwaha
- Participant ID (if applicable): NA

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Soumya-Kushwaha** [comment]
I'd like to work please.

**Comment by abhisheks008** [comment]
I want to update this repository a bit, and want to give it a fresh look. So no contributions in this project repository, you can check out the other two repos present there,
- [Deep Learning Simplified](https://github.com/World-of-ML/DL-Simplified)
- [ML-Crate](https://github.com/World-of-ML/ML-Crate)
