### ISSUE TITLE
2048 Python Game

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/Play-With-Python#44]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : 2048 Python Game</br>
:red_circle: **Aim** : Create and implement 2048 Python Game in Python.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
@Shreyg-27 comment out here to get assigned the issue first. Then you start changing your PR.

**Comment by Shreyg-27** [comment]
Can I resolve the issue now ?

**Comment by abhisheks008** [comment]
Definitely @Shreyg-27. While taking an issue comment out the approach and state that you wanna work on this issue (also follow the issue template, there you can get an idea about this). Approaching an issue like this is a good practice tbh.

Issue has been assigned to you. You can start working on the issue. Do follow the project structure given in the [Dummy Game](https://github.com/abhisheks008/Play-With-Python/tree/main/Dummy%20Game) folder. Also make sure you provide atleast 2-3 images of playing the game and represent your `README.md` file properly. For the `README.md` template, check out [here](https://github.com/abhisheks008/Play-With-Python/blob/main/Dummy%20Game/README.md).

**Comment by Shreyg-27** [comment]
> Definitely @Shreyg-27. While taking an issue comment out the approach and state that you wanna work on this issue (also follow the issue template, there you can get an idea about this). Approaching an issue like this is a good practice tbh.
> 
> Issue has been assigned to you. You can start working on the issue. Do follow the project structure given in the [Dummy Game](https://github.com/abhisheks008/Play-With-Python/tree/main/Dummy%20Game) folder. Also make sure you provide atleast 2-3 images of playing the game and represent your `README.md` file properly. For the `README.md` template, check out [here](https://github.com/abhisheks008/Play-With-Python/blob/main/Dummy%20Game/README.md).

Thank you for the guidance. I have made the changes.
