### ISSUE TITLE
Rock Paper Scissor Game

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/Play-With-Python#6]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Rock Paper Scissor Game</br>
:red_circle: **Aim** : Create a Rock Paper Scissor Game using Python programming language.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aishvi-g** [comment]
name: Aishvi Guleria
Github link : https://github.com/aishvi-g
email id : aishviguleria@gmail.com
Approach : using the random function to generate rock ,paper, scissor etc and following the basic rules of the game
program:  'IEEE Week of Code'

pls assign me this issue :)

**Comment by aishvi-g** [comment]
I want to work on this one first.

**Comment by aishvi-g** [comment]
also pls confirm if I should use tkinter package along with random package or keep it low code and use only random package?

**Comment by abhisheks008** [comment]
Sounds good to me. Issue assigned to you @aishvi-g.
Look once you are creating a game for others that needs to be user interactive, for that you need to have a user interface through which users can enjoy the game. When you are creating something, I think it would be better to put 100% on it. It's completely upto you, if you are comfortable with low code you can go for it, but if are able to do it in a better way, I'll be really happy to see that.
