### ISSUE TITLE
Sudoku Game

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/Play-With-Python#7]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Sudoku Game</br>
:red_circle: **Aim** : Create Sudoku Game using Python programming language.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by SanyaGupta19** [comment]
I wanna work on this issue

**Comment by aditi1042003** [comment]
Full name : Aditi Kesarwani 
GitHub Profile Link : https://github.com/aditi1042003
Email ID : aditi1042003@gmail.com
Participant ID (if applicable):
Approach for this Project :
Sudoku is a game played by people of every age , Making a simple interface for the game with guidance how to play.
What is your participant role? (Mention the Open Source program)
IEEE week

**Comment by abhisheks008** [comment]
Issue assigned to you @aditi1042003 
Go ahead✨

**Comment by abhisheks008** [comment]
@aditi1042003 make sure you'll be able to complete this issue by the deadline of the open source event, otherwise this will not be counted as a part of this open source event.

Best wishes!

**Comment by aditi1042003** [comment]
i am gona try to complete it today!

**Comment by abhisheks008** [comment]
Cool! Thanks for you response @aditi1042003
